title: Shiv Singh
short_logo: S.
full_logo: /assets/images/shiv_logo.png
description: My persional site
url: "https://shivsingh.netlify.app"
path: /shivsingh.net
author:
  name: Shiv Singh
  github: https://github.com/shivsingh7150
  linkedin: shivsingh7150 
  email: me@shivsingh.com
  homepage: https://www.shivsingh.com
  twitter: 

disqus_name: # Setting this will turn on Disqus comments
g_track_id: # Google Analytics tracking ID (e.g. UA-000000-2), setting this will turn on Google Analytics

markdown: kramdown

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: true
  profile: false
  startings: [html, head, body]

rss: true # RSS feed icon on or off

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  
paginate: 5
paginate_path: "/posts/page:num/"