[build]
  command = "jekyll build --trace"
  publish = "_site"
  
[[plugins]]
package = "netlify-plugin-image-optim"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404